### PR TITLE
Support roles with paths in them

### PR DESCRIPTION
**Pull request by ryanjfrizzell**
* support AWS paths in role names
  * reference: [here](https://docs.aws.amazon.com/IAM/latest/UserGuide/reference_identifiers.html#identifiers-friendly-names)
* adjust RegEx to allow for this
* minor version bump

small example of this working

```
from collections import namedtuple
import re

ROLE_ARN_REGEXP = re.compile(r"^arn:aws:iam::([0-9]{12}):role/([\w+=,.@-]+.*$)")
ParseResult = namedtuple("ArnParts", ["aws_account_id", "aws_role"])
normal = 'arn:aws:iam::584999999999:role/superNeatRole'
slashes = 'arn:aws:iam::584999999999:role/some/other/role/withSlashes'
def parse_arn(role_arn):
    return ParseResult(*ROLE_ARN_REGEXP.match(role_arn).groups())
print(type(ROLE_ARN_REGEXP))

print("###Normal")
normal_res = parse_arn(normal)
print(normal_res)

print("####Slashes")
slashes_res = parse_arn(slashes)
print(slashes_res)
```

output: 

```
###Normal
ArnParts(aws_account_id='584999999999', aws_role='superNeatRole')
####Slashes
ArnParts(aws_account_id='584999999999', aws_role='some/other/role/withSlashes')
```

### CODE REVIEW

**Comment by ryanjfrizzell** [comment]
@ionosphere80 - here that PR

**Comment by ryanjfrizzell** [comment]
@javs-perez @treyx  any chance we could get some 👀 and or comments on this?

**Comment by javs-perez** [comment]
@ryanjfrizzell we apologize for the delay in response here. We are currently working on deprecating this repo and will add a deprecation warning shortly.

We are not making any changes to the code moving forward.

**Comment by ryanjfrizzell** [comment]
> @ryanjfrizzell we apologize for the delay in response here. We are currently working on deprecating this repo and will add a deprecation warning shortly.
> 
> We are not making any changes to the code moving forward.

thanks for the quick reply @javs-perez any details on why this is going away ?

**Comment by javs-perez** [comment]
Guild Education is not using JumpCloud anymore and we are not able to debug changes in the code.

**Comment by ionosphere80** [comment]
Can someone take this project over?

**Comment by ryanjfrizzell** [comment]
> Can someone take this project over?

+1 I think we'd be happy to take over the project...

**Comment by javs-perez** [comment]
@ryanjfrizzell that's great to hear! Send me a link to the fork and I'll add it to the ReadMe. 

On a personal note, if you need a collaborator, I will gladly help.

**Comment by ryanjfrizzell** [comment]
> @ryanjfrizzell that's great to hear! Send me a link to the fork and I'll add it to the ReadMe.
> 
> On a personal note, if you need a collaborator, I will gladly help.

@javs-perez thanks! We just setup a fork here: https://github.com/CirrusMD/aws-jumpcloud

**Comment by ryanjfrizzell** [comment]
@javs-perez we've completed setup of this over on our side now: 

https://github.com/CirrusMD/aws-jumpcloud

complete with automatic homebrew updates and all.

**Comment by javs-perez** [comment]
added the info to the ReadMe, closing this PR.

**Pull request closed without merging**
